//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.1
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FeliCa2Money.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FeliCa2Money.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Bitmap Agurippa {
            get {
                object obj = ResourceManager.GetObject("Agurippa", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   日付文字列解析失敗 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CantParseDateStr {
            get {
                return ResourceManager.GetString("CantParseDateStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   カード番号を読み取れません に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CantReadCardNo {
            get {
                return ResourceManager.GetString("CantReadCardNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   カードを読むことができませんでした に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CardReadError {
            get {
                return ResourceManager.GetString("CardReadError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   確認 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Confirm {
            get {
                return ResourceManager.GetString("Confirm", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap CSV {
            get {
                object obj = ResourceManager.GetObject("CSV", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   定義ファイルエラー に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CsvRuleError {
            get {
                return ResourceManager.GetString("CsvRuleError", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap Edy {
            get {
                object obj = ResourceManager.GetObject("Edy", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   エラー に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        internal static System.Drawing.Icon Felica2Money {
            get {
                object obj = ResourceManager.GetObject("Felica2Money", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Nanaco {
            get {
                object obj = ResourceManager.GetObject("Nanaco", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   口座が選択されていません に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NoCsvAccountSelected {
            get {
                return ResourceManager.GetString("NoCsvAccountSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   CSV変換ルールが選択されていません に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NoCsvRuleSelected {
            get {
                return ResourceManager.GetString("NoCsvRuleSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   明細が一件もありません に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NoHistory {
            get {
                return ResourceManager.GetString("NoHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   CSV変換定義がありません。今すぐダウンロードしますか？ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string QueryCsvRuleDownload {
            get {
                return ResourceManager.GetString("QueryCsvRuleDownload", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap Suica {
            get {
                object obj = ResourceManager.GetObject("Suica", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap train {
            get {
                object obj = ResourceManager.GetObject("train", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   更新完了 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string UpdateCompleted {
            get {
                return ResourceManager.GetString("UpdateCompleted", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap waon {
            get {
                object obj = ResourceManager.GetObject("waon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
